platform: linux
image_resource:
  type: registry-image
inputs:
  - name: pxf_src
outputs:
  - name: pxf_artifacts
run:
  path: pxf_src/concourse/scripts/compile_pxf.bash
params:
  TARGET_OS: centos
  OUTPUT_ARTIFACT_DIR: pxf_artifacts
