platform: linux
image_resource:
  type: docker-image
inputs:
  - name: cluster_env_files
  - name: pxf_src
  - name: pxf_tarball
params:
  IMPERSONATION: true
  TARGET_OS: centos
  PXF_JVM_OPTS:
run:
  path: pxf_src/concourse/scripts/install_hadoop.bash
