platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: pxf_src
  - name: bin_gpdb
  - name: pxf_tarball
params:
  CLUSTER_NAME: hdp
  NODE: c6401.ambari.apache.org
  REALM: AMBARI.APACHE.ORG
  GROUP: smoke
  TARGET_OS: centos
run:
  path: pxf_src/concourse/scripts/test_pxf_secure.bash
