platform: linux
image_resource:
  type: docker-image
inputs:
  - name: pxf_src
  - name: cluster_env_files
  - name: bin_gpdb
  - name: pxf_tarball
  - name: dataproc_env_files
    optional: true
params:
  ACCEPTANCE:
  ACCESS_KEY_ID:
  GROUP: feature
  HIVE_VERSION: 1
  IMPERSONATION: true
  KERBEROS: false
  PXF_JVM_OPTS:
  SECRET_ACCESS_KEY:
  TARGET_OS: centos
  TARGET_OS_VERSION: 6
run:
  path: pxf_src/concourse/scripts/test_pxf_multinode.bash
