platform: linux

image_resource:
  type: registry-image

inputs:
- name: pxf_tarball
- name: pxf_src
- name: gpdb_package
- name: singlecluster
  optional: true
- name: pxf-automation-dependencies
  optional: true
- name: ambari_env_files
  optional: true

params:
  ACCESS_KEY_ID:
  BASE_PATH:
  GP_VER:
  GROUP: smoke
  HADOOP_CLIENT: HDP
  IMPERSONATION: true
  PGPORT: 5432
  PXF_BASE_DIR:
  SECRET_ACCESS_KEY:
  TEST_ENV:
  TEST_OS:
  RUN_JDK_VERSION: 8
  PROTOCOL:
  PG_REGRESS:

run:
  path: pxf_src/concourse/scripts/test.bash
