platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: pxf_src
  - name: bin_gpdb
  - name: pxf_tarball
    optional: true
params:
  ACCESS_KEY_ID:
  GROUP: smoke
  HADOOP_CLIENT: HDP
  IMPERSONATION: true
  SECRET_ACCESS_KEY:
  TARGET_OS: centos
  TARGET_OS_VERSION:
  TEST_ENV:
  TEST_OS:
run:
  path: pxf_src/concourse/scripts/test_pxf.bash
